#09/01/2025 7:51
#Jonathan Ortega
#Comment: Verificar la conexión de la BDD 
version: '3.8'

services:
  productapi:
    image: productapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=ProductDb;Username=postgres;Password=12345
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ProductDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
